global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']
  - job_name: 'apache_exporter'
    static_configs:
      - targets: ['apache_exporter:9117']
  